# Get ALL Users from API
GET http://localhost:3000/users/2

### CREATE A NEW USER
POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "Jackie",
    "username": "jchan12",
    "email": "jackie123@gmail.com"
}


### DELETE USERS
DELETE http://localhost:3000/users/25