# GETTING A TODO
GET http://localhost:3000/todos/

### GETTING TODO FOR ID 1
GET http://localhost:3000/todos/1

### POST A TODO FOR ID 1
POST http://localhost:3000/todos
Content-Type: application/json

{
    "userId": 1,
    "title": "Create a post request using soemthingsdf",
    "completed": true
}

### PUT A TODO FOR ID 1
PUT http://localhost:3000/todos/19
Content-Type: application/json

{
    "title": "Update Todo 1 request using JSON",
    "completed": false
}

### DELETE TODO ID 1
DELETE http://localhost:3000/todos/18